### PR TITLE
add missing Galaxy image

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by dannon** [comment]
@bgruening Are you using git-lfs for this?

**Comment by bgruening** [comment]
Oo, no. Ok need to read about this.

**Comment by afgane** [comment]
> Ok need to read about this.

Where?

**Comment by dannon** [comment]
https://git-lfs.github.com/

**Comment by dannon** [comment]
It should be basically -- install that git plugin, then ```git lfs install```

It won't change anything in your usage of repositories not using LFS, and it'll just work automatically on repos using it (like this one).

**Comment by afgane** [comment]
Yes, but what about the integration/use within this site - well, I guess there's nothing on that yet? I'll add some help text to the README.

**Comment by dannon** [comment]
@afgane Not sure what you mean?  Want to join in https://gitter.im/galaxyproject/Lobby?

**Comment by afgane** [comment]
What I mean is when a random person wants to add a picture to the site, how will they know to (a) use the LSF, and (b) be able to do it easily without having to read any of the LSF docs.

(I'm on the gitter channel but saw this PR before the conversation there shifted that way - plus, we'll want some docs outside that channel)

**Comment by dannon** [comment]
Ok, I see what you mean now.  I'm still trying to figure out how I expect most people to contribute.  I think, instead of local dev, it'll probably be through the GitHub interface, which would do the LFS bits automatically.  Definitely worth documenting though, @bgruening took a stab in #47

**Comment by bgruening** [comment]
@dannon if you drag and drop an image into a folder via github than it is using lfs automatically?

**Comment by dannon** [comment]
I expected that it would, but we should test this I guess.

**Comment by bgruening** [comment]
@dannon any idea how we can check that this is now added with lfs?

**Comment by dannon** [comment]
Well.  On the command line I can tell it is, per:
```
diff --git a/src/images/GalaxyNewLogo_GalaxyProject_Trans.png b/src/images/GalaxyNewLogo_GalaxyProject_Trans.png
new file mode 100644
index 00000000..0a145b96
--- /dev/null
+++ b/src/images/GalaxyNewLogo_GalaxyProject_Trans.png
@@ -0,0 +1,3 @@
+version https://git-lfs.github.com/spec/v1
+oid sha256:4c2ac4b3f0ffcb855ddf38eddc2db29b731e7790f0cb20aee0ede4768165e570
+size 56876
```

But I do not know how to do that in github, it hides this from the user quite nicely, as far as I can tell :)

**Comment by bgruening** [comment]
Ok, so it is working, good to know.

**Comment by afgane** [comment]
@bgruening you can also do `git ls-files file/path`. The file will either be listed or the output will be empty and exit code will be 1.

**Comment by bgruening** [comment]
Thanks @afgane!

**Pull request merged**
