### PR TITLE
Fix some links into the top menu

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I fixed some broken links in the top menu.

Btw, I have a question. Is it normal that some subdirectories start with a lower case letter and other with a upper case letter? 

Bérénice

### CODE REVIEW

**Comment by bebatut** [comment]
I just see that `src` directories (`events`, `news` and `support`) are used a lot of times in the pages with the first letter in upper case. Maybe is it better to change the subdirectories for upper case first letter than changing all the links. What do you think? In this case, this PR does not have any more sense

**Comment by dannon** [comment]
@bebatut Thanks!  Personally I'd like to standardize towards lowercase, let's see what other folks think though.  @clements?

**Comment by bebatut** [comment]
@dannon I could help on that :)
I tried also to fix the issue with the images but I can not fix it now (at least locally). I will try again later when I will read a bit about Metalsmith and how is it working.

**Comment by dannon** [comment]
Merging this for now to make things functional.  We should revisit standardization of directory casing, and I've made an issue for follow up at #39.

**Pull request merged**
